pipeline:
  build:
    image: centos:centos7
    commands:
      - yum -y install glib2-devel glib2 make gcc valgrind which
      - make
      - make check
      - make leak
      - make clean
      - make
      - make install
